# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\Program\CMake\bin\cmake.exe

# The command to remove a file.
RM = D:\Program\CMake\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\File\code\Qt\Ordering-System\Client\Ordering-System-Client

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\File\code\Qt\Ordering-System

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	D:\Program\CMake\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	D:\Program\CMake\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\File\code\Qt\Ordering-System\CMakeFiles D:\File\code\Qt\Ordering-System\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\File\code\Qt\Ordering-System\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ordering-System-Client

# Build rule for target.
Ordering-System-Client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Ordering-System-Client
.PHONY : Ordering-System-Client

# fast build rule for target.
Ordering-System-Client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Ordering-System-Client.dir\build.make CMakeFiles/Ordering-System-Client.dir/build
.PHONY : Ordering-System-Client/fast

#=============================================================================
# Target rules for targets named Ordering-System-Client_autogen

# Build rule for target.
Ordering-System-Client_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Ordering-System-Client_autogen
.PHONY : Ordering-System-Client_autogen

# fast build rule for target.
Ordering-System-Client_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Ordering-System-Client_autogen.dir\build.make CMakeFiles/Ordering-System-Client_autogen.dir/build
.PHONY : Ordering-System-Client_autogen/fast

Ordering-System-Client_autogen/mocs_compilation.obj: Ordering-System-Client_autogen/mocs_compilation.cpp.obj

.PHONY : Ordering-System-Client_autogen/mocs_compilation.obj

# target to build an object file
Ordering-System-Client_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Ordering-System-Client.dir\build.make CMakeFiles/Ordering-System-Client.dir/Ordering-System-Client_autogen/mocs_compilation.cpp.obj
.PHONY : Ordering-System-Client_autogen/mocs_compilation.cpp.obj

Ordering-System-Client_autogen/mocs_compilation.i: Ordering-System-Client_autogen/mocs_compilation.cpp.i

.PHONY : Ordering-System-Client_autogen/mocs_compilation.i

# target to preprocess a source file
Ordering-System-Client_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Ordering-System-Client.dir\build.make CMakeFiles/Ordering-System-Client.dir/Ordering-System-Client_autogen/mocs_compilation.cpp.i
.PHONY : Ordering-System-Client_autogen/mocs_compilation.cpp.i

Ordering-System-Client_autogen/mocs_compilation.s: Ordering-System-Client_autogen/mocs_compilation.cpp.s

.PHONY : Ordering-System-Client_autogen/mocs_compilation.s

# target to generate assembly for a file
Ordering-System-Client_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Ordering-System-Client.dir\build.make CMakeFiles/Ordering-System-Client.dir/Ordering-System-Client_autogen/mocs_compilation.cpp.s
.PHONY : Ordering-System-Client_autogen/mocs_compilation.cpp.s

clientmainwindow.obj: clientmainwindow.cpp.obj

.PHONY : clientmainwindow.obj

# target to build an object file
clientmainwindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Ordering-System-Client.dir\build.make CMakeFiles/Ordering-System-Client.dir/clientmainwindow.cpp.obj
.PHONY : clientmainwindow.cpp.obj

clientmainwindow.i: clientmainwindow.cpp.i

.PHONY : clientmainwindow.i

# target to preprocess a source file
clientmainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Ordering-System-Client.dir\build.make CMakeFiles/Ordering-System-Client.dir/clientmainwindow.cpp.i
.PHONY : clientmainwindow.cpp.i

clientmainwindow.s: clientmainwindow.cpp.s

.PHONY : clientmainwindow.s

# target to generate assembly for a file
clientmainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Ordering-System-Client.dir\build.make CMakeFiles/Ordering-System-Client.dir/clientmainwindow.cpp.s
.PHONY : clientmainwindow.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Ordering-System-Client.dir\build.make CMakeFiles/Ordering-System-Client.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Ordering-System-Client.dir\build.make CMakeFiles/Ordering-System-Client.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Ordering-System-Client.dir\build.make CMakeFiles/Ordering-System-Client.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Ordering-System-Client_autogen
	@echo ... Ordering-System-Client
	@echo ... Ordering-System-Client_autogen/mocs_compilation.obj
	@echo ... Ordering-System-Client_autogen/mocs_compilation.i
	@echo ... Ordering-System-Client_autogen/mocs_compilation.s
	@echo ... clientmainwindow.obj
	@echo ... clientmainwindow.i
	@echo ... clientmainwindow.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

